// Persist backtest output to memory/BACKTEST-RESULTS.md.
// Idempotent per run-date: re-running on the same calendar day replaces
// that date's row in the Runs table and the "Latest run" section.

import path from "node:path";
import fs from "node:fs/promises";
import { MEMORY_DIR } from "@/lib/memoryPath";
import type { BacktestResult, BacktestSummary } from "./types";
import { fmtSignedMoney } from "@/lib/format";

const FILE_NAME = "BACKTEST-RESULTS.md";

const HEADER = `# Backtest Results

Live-trade replay against current exit rules. Generated by
\`dashboard/lib/backtest/runner.ts\`. Re-runs replace the same-date row in
the Runs table and the "Latest run" detail section below.

`;

function fmtPctSimple(n: number, digits = 1): string {
  return `${n >= 0 ? "+" : ""}${n.toFixed(digits)}%`;
}

function buildRunRow(s: BacktestSummary): string {
  const ladderPct = (s.ladderFireRate * 100).toFixed(0);
  return `| ${s.runDate} | ${s.tradeCount} | ${fmtSignedMoney(s.totalActualPnl)} | ${fmtSignedMoney(s.totalSimPnl)} | ${fmtSignedMoney(s.pnlDelta)} | ${ladderPct}% |`;
}

function buildLatestSection(
  summary: BacktestSummary,
  results: BacktestResult[]
): string {
  const reasonRows = Object.entries(summary.reasonBreakdown)
    .map(([reason, count]) => `- \`${reason}\`: ${count}`)
    .join("\n");

  const tradeHeader =
    "| Symbol | Entry | Exit (sim) | Sim reason | Sim P&L | Actual P&L | Delta | Ladder |";
  const tradeSep =
    "|--------|-------|-----------|------------|---------|-----------|-------|--------|";

  const tradeRows = results
    .map((r) => {
      const entryCell = `${r.entryDate} @ \\$${r.entryPrice.toFixed(2)}`;
      const exitCell = r.simExitDate
        ? `${r.simExitDate} @ \\$${(r.simExitPrice ?? 0).toFixed(2)}`
        : "—";
      const simPnl = r.simPnl != null ? fmtSignedMoney(r.simPnl) : "—";
      // Actual P&L lookup is in summary but we pass per-trade results
      // alone. Keep this row focused on sim outputs; the dashboard does
      // the actual-vs-sim diff with full Trade objects.
      const ladderCell = r.ladderFired
        ? `↓50% @ \\$${(r.ladderFirePrice ?? 0).toFixed(2)}`
        : "—";
      return `| ${r.symbol} | ${entryCell} | ${exitCell} | \`${r.simExitReason}\` | ${simPnl} | — | — | ${ladderCell} |`;
    })
    .join("\n");

  return `## Latest run — ${summary.runDate}

**Trades replayed:** ${summary.tradeCount}
**Total actual P&L:** ${fmtSignedMoney(summary.totalActualPnl)}
**Total sim P&L:** ${fmtSignedMoney(summary.totalSimPnl)}
**Delta:** ${fmtSignedMoney(summary.pnlDelta)} (${
    summary.totalActualPnl !== 0
      ? fmtPctSimple((summary.pnlDelta / Math.abs(summary.totalActualPnl)) * 100)
      : "n/a"
  })
**Ladder fire rate:** ${(summary.ladderFireRate * 100).toFixed(0)}%

### Exit reason breakdown

${reasonRows || "- (no trades)"}

### Per-trade detail

${tradeHeader}
${tradeSep}
${tradeRows || "| — | — | — | — | — | — | — | — |"}
`;
}

// Replace any "## Runs" section with `## Runs` + the deduped row table.
// Replace any existing "## Latest run" + "### Exit reason breakdown" +
// "### Per-trade detail" subtree with the new latest-run block.
export async function writeBacktestResults(
  summary: BacktestSummary,
  results: BacktestResult[]
): Promise<void> {
  const filePath = path.join(MEMORY_DIR, FILE_NAME);
  let existing = "";
  try {
    existing = await fs.readFile(filePath, "utf8");
  } catch {
    existing = "";
  }

  // Parse out the current Runs table rows (skip duplicates of today's date).
  const runsRows: string[] = [];
  const runsHeaderRe = /^##\s+Runs\s*$/im;
  const runsMatch = existing.match(runsHeaderRe);
  if (runsMatch) {
    const idx = existing.indexOf(runsMatch[0]) + runsMatch[0].length;
    const after = existing.slice(idx);
    // Read until the next heading.
    const nextHeading = after.search(/\n##\s+/);
    const region = nextHeading === -1 ? after : after.slice(0, nextHeading);
    for (const line of region.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("|")) continue;
      // Skip header + separator (heuristic: contains "Date" or all dashes).
      if (/Date\s*\|/.test(trimmed)) continue;
      if (/^\|[\s|:-]+\|$/.test(trimmed)) continue;
      // Skip today's row — we'll insert the fresh one.
      if (trimmed.includes(`| ${summary.runDate} `)) continue;
      runsRows.push(trimmed);
    }
  }
  // Prepend today's row (most recent first).
  runsRows.unshift(buildRunRow(summary));

  const runsTable = [
    "## Runs",
    "",
    "| Date | Trades | Actual P&L | Sim P&L | Delta | Ladder rate |",
    "|------|--------|-----------|---------|-------|-------------|",
    ...runsRows,
    "",
  ].join("\n");

  const latestSection = buildLatestSection(summary, results);

  const out = HEADER + runsTable + "\n" + latestSection;
  await fs.writeFile(filePath, out, "utf8");
}
